#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-project-info-reports-plugin
Version  : 2.9
Release  : 1
URL      : https://github.com/apache/maven-project-info-reports-plugin/archive/maven-project-info-reports-plugin-2.9.tar.gz
Source0  : https://github.com/apache/maven-project-info-reports-plugin/archive/maven-project-info-reports-plugin-2.9.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-project-info-reports-plugin/2.9/maven-project-info-reports-plugin-2.9.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-project-info-reports-plugin/2.9/maven-project-info-reports-plugin-2.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep

%build

%install

%files
%defattr(-,root,root,-)
